name: nssl
description: An app for handling shopping lists

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.0.1
  intl: ^0.17.0
  file: ^6.1.0
  # intl_translation:
  shared_preferences: ^2.0.5
 # jwt:
 #   git: git://github.com/susch19/dart-json_web_token.git
  #jaguar_jwt: "^1.1.5"
  crypto: ^3.0.1 
  firebase_core: ^1.0.3
  firebase_messaging: ^9.1.1
  flutter_local_notifications: ^5.0.0+1
  http: ^0.13.1 
  sqflite: ^2.0.0+3
  permission_handler: ^6.1.1 
  scandit:
    path: ../Plugins/scandit
  # scandit_flutter_datacapture_barcode: ^6.7.0
  # scandit_flutter_datacapture_core: ^6.7.0
  # flutter_scandit: ^0.1.0
  pdf: ^3.2.0
  flutter_colorpicker: ^0.4.0 
  adaptive_theme: ^2.1.1

    #git: https://github.com/tekartik/sqflite.git

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section here, in
  # this "flutter" section, as in:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
