name: nssl
description: An app for handling shopping lists

version: 0.41.0+0

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  adaptive_theme: 
  crypto: 
  file: 
  firebase_core:
  firebase_messaging: ^15.2.7
  flutter_colorpicker: 
  flutter_hooks: 
  flutter_local_notifications: 
  flutter_riverpod: ^3.0.0-dev.16
  flutter_svg:
  hooks_riverpod: ^3.0.0-dev.16
  http: 
  intl: 
  path_provider:
  path: 
  pdf: 
  permission_handler: 
  process_run: 
  riverpod_annotation: ^3.0.0-dev.16
  scandit_flutter_datacapture_barcode: ^7.4.0
  scandit_flutter_datacapture_core: ^7.4.0
  share_handler: ^0.0.8
  shared_preferences: 
  sqlite3_flutter_libs:
  url_launcher:
  uuid:
  # scandit_flutter_datacapture_barcode: ^6.7.0
  # scandit_flutter_datacapture_core: ^6.7.0
  # flutter_scandit: ^0.1.0
  # intl_translation:
 # jwt:
 #   git: git://github.com/susch19/dart-json_web_token.git
  #jaguar_jwt: "^1.1.5"

  riverpod: any
  sqflite_common: any
  sqflite_common_ffi: any
dev_dependencies:
  build_runner:
  riverpod_lint:
  riverpod_generator: ^3.0.0-dev.16
  flutter_lints: ^6.0.0
  json_serializable: ^6.1.3 
  custom_lint: ^0.7.5

    #git: https://github.com/tekartik/sqflite.git

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/
    - assets/vectors/
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section here, in
  # this "flutter" section, as in:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
