// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2AWdZaGet1YvVgck5gZ3mww9-6NDozek',
    appId: '1:714311873087:web:7ff97d63debd5b364dbe8a',
    messagingSenderId: '714311873087',
    projectId: 'nonsuckingshoppinglist',
    authDomain: 'nonsuckingshoppinglist.firebaseapp.com',
    databaseURL: 'https://nonsuckingshoppinglist.firebaseio.com',
    storageBucket: 'nonsuckingshoppinglist.appspot.com',
    measurementId: 'G-55C6JSXQK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDY0v4Y8Ugdw0__eBIg0vA_oiVbIdPSWI',
    appId: '1:714311873087:android:ca9c27dbc69e975a',
    messagingSenderId: '714311873087',
    projectId: 'nonsuckingshoppinglist',
    databaseURL: 'https://nonsuckingshoppinglist.firebaseio.com',
    storageBucket: 'nonsuckingshoppinglist.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaNflc7mTb67r81IZP4Xpn6vkU8kto9Fc',
    appId: '1:714311873087:ios:4c24043cc62e99464dbe8a',
    messagingSenderId: '714311873087',
    projectId: 'nonsuckingshoppinglist',
    databaseURL: 'https://nonsuckingshoppinglist.firebaseio.com',
    storageBucket: 'nonsuckingshoppinglist.appspot.com',
    iosClientId: '714311873087-6830bbhihm6v74r3jvp0jfh2si59g1r9.apps.googleusercontent.com',
    iosBundleId: 'com.yourcompany.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaNflc7mTb67r81IZP4Xpn6vkU8kto9Fc',
    appId: '1:714311873087:ios:293f27fa016b99dc4dbe8a',
    messagingSenderId: '714311873087',
    projectId: 'nonsuckingshoppinglist',
    databaseURL: 'https://nonsuckingshoppinglist.firebaseio.com',
    storageBucket: 'nonsuckingshoppinglist.appspot.com',
    iosClientId: '714311873087-ch95nc16kbiuckgaogfg388vbhi3ka5n.apps.googleusercontent.com',
    iosBundleId: 'de.susch19.nssl',
  );
}
